repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-ast
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-merge-conflict
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      types: [python]
